clc;
close;
S = imread(fullpath(getIPCVpath() + "/images/morpex.png"));
figure(1);
imshow(S);
title('Original Image');
se = imcreatese('ellipse',5,5);
S2 = imopen(S,se);
S3 = imclose(S,se);
S4 = imerode(S,se);
S5= imdilate(S,se);
figure(2);
subplot(2,2,1);
imshow(S2);
title('Opening');
subplot(2,2,2);
imshow(S3);
title('Closing');
subplot(2,2,3);
imshow(S4);
title('Errosion');
subplot(2,2,4);
imshow(S5);
title('Dialtion');
